name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # - name: Run tests
      #   run: npm test

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run DEV server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          # key: ${{ secrets.PRIVATE_KEY }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: 22
          script: |
            cd Project/horeca-react
            git pull
            npm install
            npm run build
            pm2 restart horeca-react
